-- Monthly rent charges are generated by the protected rental-billing job.
-- Existing manual records deliberately remain unclassified, because they may
-- represent split or historical payments for the same lease month.
ALTER TABLE "Payment"
  ADD COLUMN "billingPeriod" DATE;

-- A partial unique index makes the automatic creation path safe to retry while
-- preserving historical, manually entered records that have no billing period.
CREATE UNIQUE INDEX "Payment_leaseId_billingPeriod_key"
  ON "Payment"("leaseId", "billingPeriod")
  WHERE "billingPeriod" IS NOT NULL;

CREATE INDEX "Payment_status_dueDate_idx"
  ON "Payment"("status", "dueDate");

CREATE INDEX "Payment_leaseId_billingPeriod_idx"
  ON "Payment"("leaseId", "billingPeriod");
