-- Monthly rent charges are generated by the protected rental-billing job.
-- Existing manual records deliberately remain unclassified, because they may
-- represent split or historical payments for the same lease month.
ALTER TABLE "Payment"
  ADD COLUMN "billingPeriod" DATE;

-- A partial unique index makes the automatic creation path safe to retry while
-- preserving historical, manually entered records that have no billing period.
CREATE UNIQUE INDEX "Payment_leaseId_billingPeriod_key"
  ON "Payment"("leaseId", "billingPeriod")
  WHERE "billingPeriod" IS NOT NULL;

CREATE INDEX "Payment_status_dueDate_idx"
  ON "Payment"("status", "dueDate");

CREATE INDEX "Payment_leaseId_billingPeriod_idx"
  ON "Payment"("leaseId", "billingPeriod");

-- Reuse the already-established CRON_SECRET stored in Supabase Vault as
-- email_retry_cron_secret. This invokes only the protected server endpoint;
-- it never creates a Checkout session or debits a tenant.
SELECT cron.schedule(
  'run-daily-rental-billing',
  '13 8 * * *',
  $$
    SELECT net.http_post(
      url := 'https://coach-johnson-realty-api-nu.vercel.app/api/internal/rental-billing/run',
      headers := jsonb_build_object(
        'Authorization',
        'Bearer ' || (
          SELECT decrypted_secret
          FROM vault.decrypted_secrets
          WHERE name = 'email_retry_cron_secret'
        )
      ),
      timeout_milliseconds := 30000
    ) AS request_id;
  $$
);
